//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApp {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsoleApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var this = $__this__;
        ///	var stunt = $__this__.getBelongStunt();
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///	
        ///	} else {
        ///		if (situation.isInitiative()) {
        ///			var me = situation.getInitiativeBS();
        ///			var targets = situation.getTargetsBS();
        ///			var action = situation.getAction();
        ///			var skillType = $.characterManager.getSkillType(&quot;Lore&quot;);
        ///			$.campaignManager.askDM(me, &quot;允许&quot; + me.getName() + &quot;使用&quot; + stunt.getName() + &quot;吗？&quot;, function(dmResult) {
        ///				if ( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt1JSCode {
            get {
                return ResourceManager.GetString("Stunt1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///	
        ///	} else {
        ///		if (!situation.isInitiative()) {
        ///			var initiative = situation.getInitiativeBS();
        ///			var me = situation.getPassiveBS();
        ///			var action = situation.getAction();
        ///			var initiativeSkillType = situation.getInitiativeSkillType();
        ///			var physiqueSkillType = $.characterManager.getSkillType(&quot;Physique&quot;);
        ///			var willSkillType = $.characterManager.getSkillType(&quot;Will&quot;);
        ///			var stunt = $__this__.getBelon [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt2JSCode {
            get {
                return ResourceManager.GetString("Stunt2JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var stunt = $__this__.getBelongStunt();
        ///	if (stunt != null) {
        ///		var me = stunt.getBelong();
        ///		var dataBackup = stunt.getCustomData();
        ///		var skillType = $__eventArgs__.passiveSkillType;
        ///		if (me == $__eventArgs__.passive.getCharacterRef()
        ///			&amp;&amp; skillType.getID() == &quot;Physique&quot;
        ///			&amp;&amp; dataBackup != null) {
        ///			me.setSkill(skillType, dataBackup);
        ///		}
        ///	}
        ///})();
        /// 的本地化字符串。
        /// </summary>
        internal static string Stunt2Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt2Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var stunt = $__this__.getBelongStunt();
        ///	if (stunt != null) {
        ///		var me = stunt.getBelong();
        ///		if (me == $__eventArgs__.passive.getCharacterRef()
        ///			&amp;&amp; $__eventArgs__.passiveCheckResult == 3) {
        ///			$__eventArgs__.passive.displayUsingStunt(stunt);
        ///			var enemy = $__eventArgs__.initiative;
        ///			var boost = $.characterManager.createAspect();
        ///			boost.setPersistenceType(2);
        ///			boost.setName(&quot;眩晕&quot;);
        ///			boost.setBenefiter(me);
        ///			boost.setBenefitTimes(1);
        ///			enemy.getCharacterRef().getAspe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt3Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt3Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///		
        ///	} else {
        ///		var me = situation.getInitiativeBS().getCharacterRef();
        ///		var consequences = me.getConsequenceList();
        ///		if (consequences != null) {
        ///			var lv2 = new Array();
        ///			var lv4 = new Array();
        ///			consequences.forEach(function (item) {
        ///				if (item.getCounteractLevel() == 2 &amp;&amp; !item.isMentalDamage()) lv2.push(item);
        ///				else if (item.getCounteractLevel() == 4&amp;&amp; !item.isMentalDamage()) lv4.push(item) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt4JSCode {
            get {
                return ResourceManager.GetString("Stunt4JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///		
        ///	} else {
        ///		var maybeMe = situation.getPassiveBS();
        ///		if (maybeMe.getCharacterRef() == $__this__.getBelongStunt().getBelong()) {
        ///			$__this__.setResult(true);
        ///		} else {
        ///			$__this__.setResult(false);
        ///		}
        ///	}
        ///})();
        /// 的本地化字符串。
        /// </summary>
        internal static string Stunt4TargetConditionJSCode {
            get {
                return ResourceManager.GetString("Stunt4TargetConditionJSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	var stunt = $__this__.getBelongStunt();
        ///	if (stunt.getCustomData() == true) {
        ///		$__this__.setResult(false);
        ///		return;
        ///	}
        ///	if (situation.isInStoryScene()) {
        ///		
        ///	} else {
        ///		var me = situation.getInitiativeBS().getCharacterRef();
        ///		if (me.getFatePoint() &gt; 0) {
        ///			var consequences = me.getConsequenceList();
        ///			var lv2Count = 0;
        ///			var lv4Count = 0;
        ///			consequences.forEach(function (item) {
        ///				if (item.getCounteractLevel() == 2 &amp;&amp; !item. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt4UsingConditionJSCode {
            get {
                return ResourceManager.GetString("Stunt4UsingConditionJSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var stunt = $__this__.getBelongStunt();
        ///	var aspect = $__eventArgs__.createdAspect;
        ///	if (stunt != null) {
        ///		var me = stunt.getBelong();
        ///		if (me != null) {
        ///			$.campaignManager.askPlayer(me, &quot;你要花费1命运点来声明你带着备用武器，使缴械特征变成增益吗？（1是，0否）&quot;, function(result) {
        ///				if (result == 1) {
        ///					$.campaignManager.askDM(me, &quot;允许&quot; + me.getName() + &quot;使用&quot; + stunt.getName() + &quot;吗？&quot;, function(dmResult) {
        ///						if (dmResult) {
        ///							aspect.setPersistenceType(2);
        ///						}
        ///					});
        ///				}
        ///			});
        ///		}
        ///	}
        ///}) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt5Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt5Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	$__this__.setResult(false);
        ///	if ($__this__.getSituation().isTriggerInvoking()) {
        ///		var me = $__eventArgs__.to;
        ///		if ($__this__.getBelongStunt().getBelong() == me.getCharacterRef()
        ///			&amp;&amp; $__eventArgs__.action == 1
        ///			&amp;&amp; ($__eventArgs__.from_checkResult == 2 || $__eventArgs__.from_checkResult == 3)) {
        ///			if (me.getCharacterRef().getFatePoint() &gt; 0) {
        ///				$__this__.setResult(true);
        ///			}
        ///		}
        ///	}
        ///})();
        /// 的本地化字符串。
        /// </summary>
        internal static string Stunt5UsingConditionJSCode {
            get {
                return ResourceManager.GetString("Stunt5UsingConditionJSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///	
        ///	} else {
        ///		if (!situation.isInitiative()) {
        ///			var initiative = situation.getInitiativeBS();
        ///			var me = situation.getPassiveBS();
        ///			var action = situation.getAction();
        ///			var initiativeSkillType = situation.getInitiativeSkillType();
        ///			var noticeSkillType = $.characterManager.getSkillType(&quot;Notice&quot;);
        ///			var investigateSkillType = $.characterManager.getSkillType(&quot;Investigate&quot;);
        ///			var stunt = $__this_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt6JSCode {
            get {
                return ResourceManager.GetString("Stunt6JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var stunt = $__this__.getBelongStunt();
        ///	if (stunt != null) {
        ///		var me = stunt.getBelong();
        ///		var dataBackup = stunt.getCustomData();
        ///		var skillType = $__eventArgs__.passiveSkillType;
        ///		if (me == $__eventArgs__.passive.getCharacterRef()
        ///			&amp;&amp; skillType.getID() == &quot;Notice&quot;
        ///			&amp;&amp; dataBackup != null) {
        ///			me.setSkill(skillType, dataBackup);
        ///		}
        ///	}
        ///})();
        /// 的本地化字符串。
        /// </summary>
        internal static string Stunt6Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt6Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///	
        ///	} else {
        ///		if (situation.isInitiative()) {
        ///			var me = situation.getInitiativeBS();
        ///			var targets = situation.getTargetsBS();
        ///			var action = situation.getAction();
        ///			var initiativeSkillType = situation.getInitiativeSkillType();
        ///			var fightSkillType = $.characterManager.getSkillType(&quot;Fight&quot;);
        ///			var athleticsSkillType = $.characterManager.getSkillType(&quot;Athletics&quot;);
        ///			var stunt = $__this__.getBelon [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt7JSCode {
            get {
                return ResourceManager.GetString("Stunt7JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var stunt = $__this__.getBelongStunt();
        ///	if (stunt != null) {
        ///		var me = stunt.getBelong();
        ///		var dataBackup = stunt.getCustomData();
        ///		var skillType = $__eventArgs__.passiveSkillType;
        ///		if (me == $__eventArgs__.passive.getCharacterRef()
        ///			&amp;&amp; skillType.getID() == &quot;Fight&quot;
        ///			&amp;&amp; dataBackup != null) {
        ///			me.setSkill(skillType, dataBackup);
        ///		}
        ///	}
        ///})();
        /// 的本地化字符串。
        /// </summary>
        internal static string Stunt7Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt7Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Stunt8Trigger1JSCode {
            get {
                return ResourceManager.GetString("Stunt8Trigger1JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///	var this = $__this__;
        ///	var stunt = $__this__.getBelongStunt();
        ///	var situation = $__this__.getSituation();
        ///	if (situation.isInStoryScene()) {
        ///	
        ///	} else {
        ///		if (situation.isInitiative()) {
        ///			var me = situation.getInitiativeBS();
        ///			var targets = situation.getTargetsBS();
        ///			var action = situation.getAction();
        ///			var skillType = $.characterManager.getSkillType(&quot;Lore&quot;);
        ///			$.campaignManager.askDM(me, &quot;允许&quot; + me.getName() + &quot;使用&quot; + stunt.getName() + &quot;吗？&quot;, function(dmResult) {
        ///				if ( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Stunt9JSCode {
            get {
                return ResourceManager.GetString("Stunt9JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Stunt9UsingConditionJSCode {
            get {
                return ResourceManager.GetString("Stunt9UsingConditionJSCode", resourceCulture);
            }
        }
    }
}
